import '../cli/questions.dart';

String generatePubspec(String appName, ProjectConfig config) {
  final dependencies = StringBuffer();
  final devDependencies = StringBuffer();

  dependencies.writeln('  flutter:');
  dependencies.writeln('    sdk: flutter');
  dependencies.writeln('  cupertino_icons: ^1.0.2');

  // State Management
  if (config.stateManagement == 'Provider') {
    dependencies.writeln('  provider: ^6.0.5');
  } else if (config.stateManagement == 'GetX') {
    dependencies.writeln('  get: ^4.6.5');
  } else if (config.stateManagement == 'Riverpod') {
    dependencies.writeln('  flutter_riverpod: ^2.3.6');
    dependencies.writeln('  riverpod_annotation: ^2.1.1');
    devDependencies.writeln('  riverpod_generator: ^2.2.3');
    devDependencies.writeln('  build_runner: ^2.4.6');
  } else if (config.stateManagement == 'Bloc') {
    dependencies.writeln('  flutter_bloc: ^8.1.3');
    dependencies.writeln('  equatable: ^2.0.5');
  } else if (config.stateManagement == 'MobX') {
    dependencies.writeln('  mobx: ^2.2.0');
    dependencies.writeln('  flutter_mobx: ^2.0.6+5');
    devDependencies.writeln('  build_runner: ^2.4.6');
    devDependencies.writeln('  mobx_codegen: ^2.3.0');
  }

  // Backend
  if (config.backend == 'Firebase') {
    dependencies.writeln('  firebase_core: ^2.15.1');
    dependencies.writeln('  firebase_auth: ^4.7.3');
    dependencies.writeln('  cloud_firestore: ^4.8.5');
  } else if (config.backend == 'Supabase') {
    dependencies.writeln('  supabase_flutter: ^1.10.3');
  } else if (config.backend == 'Appwrite') {
    dependencies.writeln('  appwrite: ^9.0.1');
  }

  // Router
  if (config.router == 'GoRouter') {
    dependencies.writeln('  go_router: ^10.0.0');
  } else if (config.router == 'GetX Routing') {
    if (config.stateManagement != 'GetX') {
      dependencies.writeln('  get: ^4.6.5');
    }
  }

  // Common Utils
  dependencies.writeln('  google_fonts: ^5.1.0');
  dependencies.writeln('  flutter_svg: ^2.0.7');

  return '''
name: $appName
description: A new Flutter project generated by CUFS.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
${dependencies.toString()}

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
${devDependencies.toString()}

flutter:
  uses-material-design: true
''';
}
